- name: Deploy Docker
  hosts: all
  become: true

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Docker
      shell: apt install docker.io -y 
      become: true

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: true

    - name: Create app directory
      file:
        path: /home/ubuntu/samplesite
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy application files to EC2
      copy:
        src: ../samplesite/
        dest: /home/ubuntu/samplesite/
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Build Docker image
      command: docker build -t samplesite /home/ubuntu/samplesite
      args:
        chdir: /home/ubuntu/samplesite

    - name: Run Docker container
      command: docker run -d --name samplesite -p 80:80 samplesite
